---
- hosts: all
  remote_user: root

  tasks:
  - name: debug
    debug: "msg=ansible_hostname: {{ ansible_hostname }} ansible_host: {{ ansible_host }} hostname: {{ hostname }}"

  - name: clean up host {{ ansible_hostname }} setup
    file: path=/tmp/{{ ansible_hostname }} state=absent
